version: '3'
services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
  postgres:
      image: postgres
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
      volumes:
        - ./db-init:/docker-entrypoint-initdb.d        
      ports:
        - "5432:5432"